# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0168ee559fa81aa5f23e701bd3c64cf0f66ce48ec594184036fe4b608ce99ad3e51a450d42346566549bfeec4404f795e86c4092bd9b5f0b0ef943758994e718

test:
  secret_key_base: a8ae90d7775b65f61391bdb258dcfcc43877fc0a68e165a60f8ffcf118616518e9d814fdea049321a2dff98d0e006f87cd5e3c5ac804b9b717f79a7d882d2308

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
